# Generated by Django 3.2.3 on 2021-06-06 17:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210606_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='end_date',
            field=models.DateTimeField(default=core.models.default_end_time, verbose_name='Auction end date'),
        ),
    ]
