KIND_OF_PET_CAT = 1
KIND_OF_PET_HEDGEHOG = 2
KINDS_OF_PET = (
    (KIND_OF_PET_CAT, 'cat'),
    (KIND_OF_PET_HEDGEHOG, 'hedgehog')
)

LOT_STATUS_ACTIVE = 1
LOT_STATUS_CLOSED = 2
LOT_STATUS_INACTIVE = 3
LOT_STATUSES = (
    (LOT_STATUS_ACTIVE, 'active'),
    (LOT_STATUS_CLOSED, 'closed'),
    (LOT_STATUS_INACTIVE, 'inactive')
)